# Generated by Django 5.1.3 on 2024-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('steps', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('hrv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('entry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('duration', models.FloatField(help_text='Duration of sleep in hours')),
                ('disturbances', models.IntegerField(help_text='Number of disturbances during sleep')),
                ('sleep_quality', models.FloatField(default=0.0, help_text='Quality of sleep on a scale of 0-100')),
            ],
        ),
    ]
